version: "3.9"

services:
  pagopa-ecommerce-payment-instruments-service:
    container_name: pagopa-ecommerce-payment-instruments-service
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce
    env_file: .env

  mongo:
    container_name: pagopa-ecommerce-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - pagopa-ecommerce
    healthcheck:
      test: echo "db.stats().ok" | mongo --quiet
      interval: 10s

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - pagopa-ecommerce
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@pagopa-ecommerce-mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

networks:
  pagopa-ecommerce:
    name: pagopa-ecommerce
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450