apiVersion: v2
name: pagopa-ecommerce-payment-instruments-service
description: Microservice to handle payment instruments in ecommerce pagoPA
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.15.0
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
